post_install() {
    systemctl start logmein-hamachi
    echo "To automatically start the LogMeIn Hamachi service when your system boots, execute 'systemctl enable hamachi'"
    echo "To allow a standard user to control LogMeIn Hamachi, add 'Ipc.User <login name>' to '/var/lib/logmein-hamachi/h2-engine-override.cfg' and restart the service."
}

post_upgrade() {
    post_install
}

pre_remove() {
    systemctl stop logmein-hamachi
}
