post_install() {
  modprobe tun
  systemctl start logmein-hamachi
  echo "To automatically start the LogMeIn Hamachi service when your system boots, execute 'systemctl enable logmein-hamachi.'"
}

post_upgrade() {
  systemctl start logmein-hamachi
}

pre_upgrade() {
  systemctl stop logmein-hamachi
  rm -rf /var/run/logmein-hamachi
}

pre_remove() {
  systemctl stop logmein-hamachi
  rm -rf /var/run/logmein-hamachi
}
